version: '3.1'

services:

  api:
    restart: on-failure
    build: api/
    environment:
      REQUEST_TIMEOUT: 30
      FILE_FOLDER: /home/app/files
    volumes:
      - ./files:/home/app/files

  nginx:
    image: nginx:1.18-alpine
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./files:/home/app/files
    depends_on:
      - api
