version: "3.1"

services:

  api:
    build: .
    restart: on-failure
    environment:
      STORAGE_DIRECTORY: /files
    volumes:
      - ./files:/files
    networks:
      - <network_name>

networks:
  <network_name>:
    external: true
