version: "3.1"

services:

  api:
    build: .
    restart: on-failure
    environment:
      STORAGE_DIRECTORY: /files
    volumes:
      - ./files:/files

  nginx:
    image: nginx:1.23.1-alpine
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./files:/home/app/files
    depends_on:
      - api
