version: "3.1"

services:

  files:
    build: api/
    restart: on-failure
    environment:
      REQUEST_TIMEOUT_TOTAL: 30
      FILE_FOLDER: /files
    volumes:
      - ./files:/files

  nginx:
    image: nginx:1.23.1-alpine
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./files:/home/app/files
    depends_on:
      - api
